### ISSUE TITLE
轮播能不能上下滚动

### ISSUE THREAD

**Issue by peiniwan** [cpacm/SimpleSlider#10]
您好，这个轮播能不能上下滚动，没有的话如何实现呢

**Comment by cpacm** [comment]
上下不能滚动。
至于如何上下滚动，我看到过一个很巧妙的处理方法：将手势动作的x,y坐标互换，以致当我们向上滑动时其实是向右滑。然后通过Transformer做Y轴的转场动画。
具体的可以看看 https://github.com/kaelaela/VerticalViewPager

**Comment by peiniwan** [comment]
好的，谢谢
