### ISSUE TITLE
严重问题

### ISSUE THREAD

**Issue by ProgrammerApe** [cpacm/SimpleSlider#2]
第一次运行可以正常 执行    第二次布局会报错

![qq 20160715164118](https://cloud.githubusercontent.com/assets/20274230/16868585/0af2fe26-4aab-11e6-866c-5a2668e924ad.png)

![qq 20160715164309](https://cloud.githubusercontent.com/assets/20274230/16868617/3dd87316-4aab-11e6-9575-4b9994f4ff88.png)

**Comment by cpacm** [comment]
能告知使用的机型和贴出使用的代码吗？
